# Generated by Django 4.2.2 on 2023-07-04 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
