# Generated by Django 4.2.2 on 2023-07-04 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='DominoStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cocinero',
            fields=[
                ('dominostaff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.dominostaff')),
            ],
            bases=('polls.dominostaff',),
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('dominostaff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.dominostaff')),
            ],
            bases=('polls.dominostaff',),
        ),
    ]
